#!/usr/bin/env bash
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../lib/uk_common.sh"

PS_TYPE=''
PS_NAME=''
PS_DEST='.'
PS_FORCE=0

ps_usage() {
  cat <<'USAGE'
Usage:
  _project_scaffold.sh --type TYPE --name NAME [--dest DIR] [--force]

Types:
  bash, python-flask, node-cli, go-service
USAGE
}
ps_write_common() {
  local dir="$1" title="$2"
  mkdir -p "$dir/.github/workflows"
  cat >"$dir/README.md" <<__README__
# $title

Generated by UtilityKit Project Scaffold.
__README__
  cat >"$dir/Makefile" <<'__MAKE__'
.PHONY: run test lint format
run:
	@echo "Define project-specific run target"
test:
	@echo "Define project-specific tests"
lint:
	@echo "Define lint command"
format:
	@echo "Define formatter command"
__MAKE__
  cat >"$dir/.github/workflows/ci.yml" <<'__CI__'
name: CI
on:
  push:
  pull_request:
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Customize this workflow for your project"
__CI__
}
ps_gen_bash() {
  local dir="$1"
  cat >"$dir/.gitignore" <<'__GI__'
*.log
.env
__GI__
  cat >"$dir/Dockerfile" <<'__DOCKER__'
FROM bash:5.2
WORKDIR /app
COPY . .
CMD ["bash", "main.sh"]
__DOCKER__
  cat >"$dir/main.sh" <<'__BASH__'
#!/usr/bin/env bash
set -euo pipefail
echo "Hello from your new Bash tool"
__BASH__
  chmod +x "$dir/main.sh"
}
ps_gen_python_flask() {
  local dir="$1"
  mkdir -p "$dir/app"
  cat >"$dir/.gitignore" <<'__GI__'
__pycache__/
.venv/
.env
__GI__
  cat >"$dir/requirements.txt" <<'__REQ__'
Flask==3.1.0
gunicorn==23.0.0
__REQ__
  cat >"$dir/Dockerfile" <<'__DOCKER__'
FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
CMD ["gunicorn", "-b", "0.0.0.0:8000", "app.main:app"]
__DOCKER__
  cat >"$dir/app/main.py" <<'__PYAPP__'
from flask import Flask
app = Flask(__name__)

@app.get('/')
def index():
    return {'message': 'Hello from UtilityKit scaffold'}
__PYAPP__
}
ps_gen_node_cli() {
  local dir="$1" slug
  slug="$(uk_slugify "$PS_NAME")"
  cat >"$dir/.gitignore" <<'__GI__'
node_modules/
.env
__GI__
  cat >"$dir/package.json" <<__PKG__
{
  "name": "$slug",
  "version": "0.1.0",
  "type": "module",
  "bin": {
    "$slug": "index.js"
  },
  "scripts": {
    "start": "node index.js"
  }
}
__PKG__
  cat >"$dir/Dockerfile" <<'__DOCKER__'
FROM node:22-alpine
WORKDIR /app
COPY package.json ./
RUN npm install --package-lock=false
COPY . .
CMD ["node", "index.js"]
__DOCKER__
  cat >"$dir/index.js" <<'__JS__'
#!/usr/bin/env node
console.log('Hello from your UtilityKit Node CLI scaffold');
__JS__
  chmod +x "$dir/index.js"
}
ps_gen_go_service() {
  local dir="$1"
  mkdir -p "$dir/cmd/service"
  cat >"$dir/.gitignore" <<'__GI__'
bin/
.env
__GI__
  cat >"$dir/go.mod" <<__GOMOD__
module $(uk_slugify "$PS_NAME")

go 1.23
__GOMOD__
  cat >"$dir/Dockerfile" <<'__DOCKER__'
FROM golang:1.23-alpine AS build
WORKDIR /src
COPY . .
RUN go build -o /out/service ./cmd/service
FROM alpine:3.20
COPY --from=build /out/service /service
CMD ["/service"]
__DOCKER__
  cat >"$dir/cmd/service/main.go" <<'__GO__'
package main

import "fmt"

func main() {
    fmt.Println("Hello from your UtilityKit Go service scaffold")
}
__GO__
}
ps_main() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
    --type)
      shift
      PS_TYPE="${1:-}"
      ;;
    --name)
      shift
      PS_NAME="${1:-}"
      ;;
    --dest)
      shift
      PS_DEST="${1:-}"
      ;;
    --force) PS_FORCE=1 ;;
    -h | --help)
      ps_usage
      return 0
      ;;
    *)
      uk_error "Unknown option: $1"
      return 1
      ;;
    esac
    shift
  done
  if [[ -z "$PS_TYPE" && -t 0 ]]; then
    uk_header 'UtilityKit Project Scaffold' 'Generate standardized starter projects'
    PS_TYPE="$(uk_prompt 'Enter scaffold type (bash, python-flask, node-cli, go-service)' 'bash' 'python-flask' 'Each scaffold creates starter files, CI boilerplate, and a minimal runtime entrypoint.')"
    PS_NAME="$(uk_prompt 'Enter the project folder name to generate' '' 'demo-app' 'This becomes the directory name inside the destination folder.')"
    PS_DEST="$(uk_prompt 'Enter the parent destination directory' '.' '~/projects' 'The new scaffold folder will be created inside this destination.')"
  fi

  [[ -n "$PS_TYPE" && -n "$PS_NAME" ]] || {
    ps_usage
    return 1
  }
  if [[ "$PS_NAME" == "." || "$PS_NAME" == ".." || "$PS_NAME" == /* || "$PS_NAME" == */* || "$PS_NAME" == -* ]]; then
    uk_error "Unsafe project name: $PS_NAME"
    return 1
  fi
  PS_DEST="$(uk_abs_path "${PS_DEST:-.}")"
  local out="$PS_DEST/$PS_NAME"
  if [[ -e "$out" && $PS_FORCE -ne 1 ]]; then
    uk_error "Target already exists: $out"
    return 1
  fi

  [[ -n "$out" && "$out" != "/" ]] || {
    uk_error "Refusing unsafe target path: $out"
    return 1
  }
  rm -rf -- "$out"
  mkdir -p -- "$out"
  ps_write_common "$out" "$PS_NAME"
  case "$PS_TYPE" in
  bash) ps_gen_bash "$out" ;;
  python-flask) ps_gen_python_flask "$out" ;;
  node-cli) ps_gen_node_cli "$out" ;;
  go-service) ps_gen_go_service "$out" ;;
  *)
    uk_error "Unsupported type: $PS_TYPE"
    return 1
    ;;
  esac
  uk_success "Generated $PS_TYPE scaffold at $out"
}
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  set -euo pipefail
  ps_main "$@"
fi
